---
### group_vars/CONNECTED_ENDPOINTS.yml

# Definition of connected endpoints in the fabric.
servers:
  # Name of the defined server.
  - name: dc1-server1
    # Definition of adapters on the server.
    adapters:
      # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [ eth1 ]
        # Device ports where the server ports are connected.
        switch_ports: [ Ethernet3 ]
        # Device names where the server ports are connected.
        switches: [ dc1-leaf1 ]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        # port_channel:
        #   # Description of the port channel interface.
        #   description: PortChannel dc1-leaf1-server1
        #   # Port channel mode for LACP.
        #   mode: active
        #   short_esi: 0001:1011:1011

      # - endpoint_ports: [ iLO ]
      #   switch_ports: [ Ethernet5 ]
      #   switches: [ dc1-leaf1c ]
      #   vlans: 11
      #   mode: access
      #   spanning_tree_portfast: edge

  - name: dc1-server2
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ dc1-leaf2a, dc1-leaf2b ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel dc1-server2
          mode: active
      - endpoint_ports: [ eth3 ]
        switch_ports: [ Ethernet3 ]
        switches: [ dc1-leaf2c ]
        vlans: 11
        mode: access
        spanning_tree_portfast: edge


  # Start of definitions for DC2 (identical to DC1)

  # Name of the defined server.
  - name: dc2-erver1
    # Definition of adapters on the server.
    adapters:
      # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [ eth1 ]
        # Device ports where the server ports are connected.
        switch_ports: [ Ethernet3 ]
        # Device names where the server ports are connected.
        switches: [ dc2-leaf1 ]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        # port_channel:
        #   # Description of the port channel interface.
        #   description: PortChannel dc2-leaf1-server1
        #   # Port channel mode for LACP.
        #   mode: active
        #   short_esi: 0002:1011:1011

      # - endpoint_ports: [ iLO ]
      #   switch_ports: [ Ethernet5 ]
      #   switches: [ dc2-leaf1c ]
      #   vlans: 11
      #   mode: access
      #   spanning_tree_portfast: edge

  - name: dc2-server2
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ dc2-leaf2a, dc2-leaf2b ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel dc2-server2
          mode: active
      - endpoint_ports: [ eth3 ]
        switch_ports: [ Ethernet3 ]
        switches: [ dc2-leaf2c ]
        vlans: 11
        mode: access
        spanning_tree_portfast: edge
